- name: Setup NXOS timezone with ntp configuration
  hosts: nxos
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: nxos

  tasks:
    - name: ntp configuration
      nxos_config:
        lines: 'ntp server 192.168.1.25 use-vrf management'
        save: yes
    - name: timezone to UTC 9 0
      nxos_config:
        lines: 'clock  timezone UTC 9 0'
        save: yes
