# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant_API_Version = "2"
Vagrant.configure(Vagrant_API_Version) do |config|

  #================#
  # Ansible Server #
  #================#
  
  config.vm.define "ansible-server24" do |cfg|
    cfg.vm.box = "centos/7"
 	cfg.vm.provider "virtualbox" do |vb|
	  vb.name = "Ansible-Server2.4(github_SysNet4Admin)"
	end
	cfg.vm.host_name = "ansible-server24"
	cfg.vm.network "public_network", ip: "192.168.1.24"
	cfg.vm.network "forwarded_port", guest: 22, host: 60024, auto_correct: true, id: "ssh"
	cfg.vm.synced_folder "../data", "/vagrant", disabled: true
	cfg.vm.provision "shell", inline: "yum install ansible -y"
	cfg.vm.provision "file", source: "ansible_env_ready.yml", 
	  destination: "ansible_env_ready.yml"
	cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  end
  
  config.vm.define "ansible-server25" do |cfg|
    cfg.vm.box = "centos/7"
 	cfg.vm.provider "virtualbox" do |vb|
	  vb.name = "Ansible-Server2.5(github_SysNet4Admin)"
	end
	cfg.vm.host_name = "ansible-server25"
	cfg.vm.network "public_network", ip: "192.168.1.25"
	cfg.vm.network "forwarded_port", guest: 22, host: 60025, auto_correct: true, id: "ssh"
	cfg.vm.synced_folder "../data", "/vagrant", disabled: true
	cfg.vm.provision "shell", inline: "yum install epel-release -y"
	cfg.vm.provision "shell", inline: "yum install ansible -y"
	cfg.vm.provision "file", source: "ansible_env_ready.yml", 
	  destination: "ansible_env_ready.yml"
	cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  end
end
